#only test invalid maps

./cub3D maps/invalid_color1.cub
./cub3D maps/invalid_color2.cub
./cub3D maps/invalid_color3.cub
./cub3D maps/invalidmap_direct_2xpm.cub
./cub3D maps/invalidmap_doubledirect.cub
./cub3D maps/invalidmap_dupplayer.cub
./cub3D maps/invalidmap_elementdup.cub
./cub3D maps/invalidmap_empty.cub
./cub3D maps/invalidmap_minus.cub
./cub3D maps/invalidmap_newline.cub
./cub3D maps/invalidmap_noplayer.cub
./cub3D maps/invalidmap_space.cub
./cub3D maps/invalidmap.cbu
./cub3D maps/invalidmap_nowall_left.cub
./cub3D maps/invalidmap_nowall_right.cub
./cub3D maps/invalidmap_nowall_top.cub
./cub3D maps/invalidmap_nowall_bottom.cub
./cub3D maps/.cub
./cub3D maps/a.cub.cub
./cub3D maps/cub
./cub3D maps/hanarekojima1.cub
./cub3D maps/hanarekojima2.cub
./cub3D maps/hanarekojima3.cub
./cub3D maps/hanarekojima4.cub
./cub3D maps/hanarekojima5.cub
./cub3D maps/hanarekojima6.cub
./cub3D maps/leftS.cub
./cub3D maps/rightW.cub
./cub3D maps/topN.cub
./cub3D maps/underN.cub
./cub3D maps/less_dirgb1.cub
./cub3D maps/less_dirgb2.cub
